# Site settings
title: Infodiver
#email: hi@infodiver.ru
description: > # this means to ignore newlines until "baseurl:"
   Some fineArt brought by travelling free artist and occasionally blog writings about travelling in Russia besides other stuff. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://infodiver.ru" # the base hostname & protocol for your site
twitter_username: infodiverblog
github_username:  infodiver
author: Alexander Fields

# Build settings
markdown: kramdown
permalink: "/:title"

collections:
  fineart:
    title: fineArt
    description: pictures in watercolor, gouache and digital mixed with analog
    output: true
    permalink: /fineart/:path/

defaults:
  - scope:
      path: ""
      type: insights
    values:
      layout: page
