# Site settings
title: Infodiver
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   Here you may find some Art and read about it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://infodiver.ru" # the base hostname & protocol for your site
twitter_username: infodiverblog
github_username:  infodiver

# Build settings
markdown: kramdown
permalink: "/:title"

collections:
  insights:
    title: Озарения
    description: Озарения в виде историй и размышлений
    output: true
    permalink: /insights/:path/

  fineart:
    title: fineArt
    description: pictures in watercolor, gouache and digital mixed with analog
    output: true
    permalink: /fineart/:path/

defaults:
  - scope:
      path: ""
      type: insights
    values:
      layout: page
