# Site settings
title: Инфодайвер.ру
#email: hi@infodiver.ru
description: > # this means to ignore newlines until "baseurl:"
   Один берёт часы — остальные хотят калькулятор. А китаец нарезает LCD прямоугольниками
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://infodiver.ru" # the base hostname & protocol for your site
twitter_username: infodiver_ru
#github_username: infodiver
author: Данила

# Build settings
markdown: kramdown
permalink: "/:title"

collections:
  fineart:
    title: fineArt
    description: pictures in watercolor, gouache and digital mixed with analog
    output: true
    permalink: /fineart/:path/

defaults:
  - scope:
      path: ""
      type: insights
    values:
      layout: page
